### ISSUE TITLE
Redirecionamento incorreto ao tentar criar uma conta

### ISSUE THREAD

**Issue by LuisGomes18** [LuisGomes18/PAP#25]
**Descreva o bug**
Quando tento ir para o "signup", ele redireciona diretamente para o "login", não permitindo criar uma conta. Não havia nenhuma conta logada nas tentativas.

**Para Reproduzir**
Passos para reproduzir o comportamento:
1. Ir para index ou /
2. Clicar no botao de singup
3. Erro ta no redirecionamento

**Comportamento Esperado**
Deveria ser redirecionado para a página de criação de conta.

**Capturas de tela**
Sem

**Computador:**
 - Sistema Operacional: Ubuntu 22.04.4 LTS
 - Navegador: Chrome
 - Versão: 123.0.6312.105 64 bits

**Smartphone (por favor, preencha as seguintes informações):**
 - Dispositivo: OPPO A17
 - Sistema Operacional: Android 12 ColorOS V12.1
 - Navegador: Chrome
 - Versão: 123.0.6312.99

**Contexto Adicional**
O redirecionamento ocorre com problemas no computador, mas no smartphone, o mesmo erro não acontece.

**Comment by LuisGomes16** [comment]
Bug Resolvido depois de limpar o historico, cookies e dados do site
